Container factory method
Monsterholic/mercury pull request #32
Opened 2020-02-26 01:43 UTC by darlison-alves

Container class created to manage "Handler class" and dependency injection in the same.
How exemple, I writed some tests....

2020-02-29 22:40 UTC, cl3dson commented
Many new issues in codify code quality review, please could you check some of them?

2020-03-03 18:18 UTC, noamcore commented
You could just see in the details [here](https://app.codacy.com/manual/f.cl3dson/mercury/pullRequest?prid=5070860) and fix the issues.

Before the merge, please squash them up or use a fixup. This is required to remove the "fix" commits that don't have helpful messages.

2020-03-03 18:19 UTC, iagosrodrigues requested changes
Have to fix the Codacy issues before merge.

2020-03-04 21:33 UTC, noamcore commented
I'll see this at the weekend.

2020-03-12 00:56 UTC, noamcore commented on lib/connection/RabbitMQConnectionFacade.ts
> +
I think you should remove the commented code as well.
```suggestion
```

2020-03-12 00:58 UTC, iagosrodrigues requested changes
Here more tips.

2020-03-12 00:58 UTC, noamcore commented on lib/connection/RabbitMQConnectionFacade.ts
> +                    //const handler = handlers.get(handlerClassName);
Here too.
```suggestion
                if (handler) {
```

2020-03-18 14:20 UTC, merged